/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package V2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import java.util.HashSet;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nann Koungkea
 */
public class AutomataProject extends javax.swing.JFrame {
    private FA newFa;
    private DFA newDFA;
    /**
     * Creates new form AutomataProject
     */
    public AutomataProject() {
        initComponents();
    }
    
    private static final String DB_FILE_PATH = "AutomataDB.csv";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadFAPanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SavedDBtable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sStateTf1 = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        checkDeterministic2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        label6 = new java.awt.Label();
        Home2 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        jButton8 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NumFStateTf = new java.awt.TextField();
        numStatestf = new java.awt.TextField();
        alphaTF = new java.awt.TextField();
        sStateTf = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        allTransTf = new java.awt.TextField();
        NumTransTf = new java.awt.TextField();
        fStatesTf = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        checkSavePanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        label8 = new java.awt.Label();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        convertPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        label7 = new java.awt.Label();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        checkAcDFA = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        testStringTf1 = new java.awt.TextField();
        jButton25 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadFAPanel.setMinimumSize(new java.awt.Dimension(686, 452));
        loadFAPanel.setPreferredSize(new java.awt.Dimension(686, 452));
        loadFAPanel.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(102, 51, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel18)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(16, 16, 16))
        );

        loadFAPanel.add(jPanel12);
        jPanel12.setBounds(0, 0, 687, 54);

        jButton13.setBackground(new java.awt.Color(0, 102, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Load");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        loadFAPanel.add(jButton13);
        jButton13.setBounds(590, 410, 83, 42);

        SavedDBtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Num State", "Alphabets", "Start State", "NumTrans", "Num Final State", "Final State(s)", "Transition"
            }
        ));
        jScrollPane1.setViewportView(SavedDBtable);

        loadFAPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 660, 290);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("AUTOMATION");
        loadFAPanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 96, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("All saved FA in the database:");
        loadFAPanel.add(jLabel6);
        jLabel6.setBounds(220, 70, 250, 25);

        sStateTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sStateTf1ActionPerformed(evt);
            }
        });
        loadFAPanel.add(sStateTf1);
        sStateTf1.setBounds(440, 410, 110, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Enter ID you want to load:");
        loadFAPanel.add(jLabel14);
        jLabel14.setBounds(260, 410, 180, 20);

        jButton15.setBackground(new java.awt.Color(102, 102, 255));
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Back");
        jButton15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        loadFAPanel.add(jButton15);
        jButton15.setBounds(10, 410, 83, 42);

        loadFAPanel.setVisible(false);

        getContentPane().add(loadFAPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 51, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(294, 294, 294))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(16, 16, 16))
        );

        jButton14.setBackground(new java.awt.Color(102, 51, 255));
        jButton14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Check Deterministic");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Back");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label6.setText("Next Step:");

        checkDeterministic2.setVisible(false);

        javax.swing.GroupLayout checkDeterministic2Layout = new javax.swing.GroupLayout(checkDeterministic2);
        checkDeterministic2.setLayout(checkDeterministic2Layout);
        checkDeterministic2Layout.setHorizontalGroup(
            checkDeterministic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkDeterministic2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(checkDeterministic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkDeterministic2Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkDeterministic2Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkDeterministic2Layout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))))
        );
        checkDeterministic2Layout.setVerticalGroup(
            checkDeterministic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkDeterministic2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(checkDeterministic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel2.setBackground(new java.awt.Color(204, 204, 204));
        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setForeground(new java.awt.Color(255, 255, 255));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 0, 102));
        label2.setText("Getting start on designing Finite Automata");

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("Click to start");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(102, 102, 255));
        label4.setName(""); // NOI18N
        label4.setText("I3_GIC_Group 6 ");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel4.setBackground(new java.awt.Color(102, 51, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FINITE AUTOMATION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(294, 294, 294))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(16, 16, 16))
        );

        Home2.setVisible(true);

        javax.swing.GroupLayout Home2Layout = new javax.swing.GroupLayout(Home2);
        Home2.setLayout(Home2Layout);
        Home2Layout.setHorizontalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        Home2Layout.setVerticalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(Home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        Main.setPreferredSize(new java.awt.Dimension(686, 452));
        Main.setLayout(null);
        Main.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Number of states:");
        Main.add(jLabel1);
        jLabel1.setBounds(20, 60, 181, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Number of Final State:");
        Main.add(jLabel2);
        jLabel2.setBounds(40, 190, 150, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seperated by comma (ex: 0 a 1,1 b 2)");
        jLabel3.setToolTipText("");
        Main.add(jLabel3);
        jLabel3.setBounds(10, 310, 270, 30);
        jLabel3.getAccessibleContext().setAccessibleName("Enter transitions (fromState input toState) \n(seperated by comma):");

        jButton1.setBackground(new java.awt.Color(102, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Load FA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Main.add(jButton1);
        jButton1.setBounds(250, 400, 131, 42);

        jPanel3.setBackground(new java.awt.Color(102, 51, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(16, 16, 16))
        );

        Main.add(jPanel3);
        jPanel3.setBounds(0, 0, 683, 42);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Main.add(jButton2);
        jButton2.setBounds(6, 399, 83, 42);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Alphabet (space-sapareted):");
        Main.add(jLabel4);
        jLabel4.setBounds(20, 100, 170, 20);

        NumFStateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumFStateTfActionPerformed(evt);
            }
        });
        Main.add(NumFStateTf);
        NumFStateTf.setBounds(190, 190, 110, 30);
        NumFStateTf.getAccessibleContext().setAccessibleName("");

        numStatestf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numStatestfActionPerformed(evt);
            }
        });
        Main.add(numStatestf);
        numStatestf.setBounds(210, 60, 200, 30);

        alphaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaTFActionPerformed(evt);
            }
        });
        Main.add(alphaTF);
        alphaTF.setBounds(210, 100, 200, 30);
        alphaTF.getAccessibleContext().setAccessibleName("");

        sStateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sStateTfActionPerformed(evt);
            }
        });
        Main.add(sStateTf);
        sStateTf.setBounds(190, 150, 110, 30);
        sStateTf.getAccessibleContext().setAccessibleName("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Start State:");
        Main.add(jLabel7);
        jLabel7.setBounds(110, 150, 70, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Final State(s)(space-seperated):");
        Main.add(jLabel8);
        jLabel8.setBounds(310, 190, 190, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Number of transitions:");
        Main.add(jLabel9);
        jLabel9.setBounds(360, 150, 150, 20);

        allTransTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTransTfActionPerformed(evt);
            }
        });
        Main.add(allTransTf);
        allTransTf.setBounds(290, 260, 390, 120);
        allTransTf.getAccessibleContext().setAccessibleName("");

        NumTransTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTransTfActionPerformed(evt);
            }
        });
        Main.add(NumTransTf);
        NumTransTf.setBounds(510, 150, 110, 30);
        NumTransTf.getAccessibleContext().setAccessibleName("");

        fStatesTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fStatesTfActionPerformed(evt);
            }
        });
        Main.add(fStatesTf);
        fStatesTf.setBounds(510, 190, 110, 30);
        fStatesTf.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Enter transitions (fromState input toState):");
        jLabel5.setToolTipText("");
        Main.add(jLabel5);
        jLabel5.setBounds(10, 280, 270, 30);

        jButton3.setBackground(new java.awt.Color(102, 51, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Design FA");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Main.add(jButton3);
        jButton3.setBounds(540, 400, 131, 42);

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Main.getAccessibleContext().setAccessibleName("");

        jPanel11.setBackground(new java.awt.Color(102, 51, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(16, 16, 16))
        );

        jButton10.setBackground(new java.awt.Color(102, 102, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Back");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label8.setText("Next Step:");

        jButton21.setBackground(new java.awt.Color(102, 51, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Check Acceptance");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(102, 51, 255));
        jButton22.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Save DFA");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        checkSavePanel2.setVisible(false);

        javax.swing.GroupLayout checkSavePanel2Layout = new javax.swing.GroupLayout(checkSavePanel2);
        checkSavePanel2.setLayout(checkSavePanel2Layout);
        checkSavePanel2Layout.setHorizontalGroup(
            checkSavePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(checkSavePanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(checkSavePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        checkSavePanel2Layout.setVerticalGroup(
            checkSavePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkSavePanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(checkSavePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel10.setBackground(new java.awt.Color(102, 51, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(294, 294, 294))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(16, 16, 16))
        );

        jButton7.setBackground(new java.awt.Color(102, 102, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label7.setText("Next Step:");

        jButton19.setBackground(new java.awt.Color(102, 51, 255));
        jButton19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Convert DFA to NFA");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(102, 51, 255));
        jButton20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Check and Save FA");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(102, 51, 255));
        jButton23.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Minimize DFA");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        convertPanel2.setVisible(false);

        javax.swing.GroupLayout convertPanel2Layout = new javax.swing.GroupLayout(convertPanel2);
        convertPanel2.setLayout(convertPanel2Layout);
        convertPanel2Layout.setHorizontalGroup(
            convertPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(convertPanel2Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(convertPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanel2Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanel2Layout.createSequentialGroup()
                        .addGroup(convertPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(235, 235, 235))))
        );
        convertPanel2Layout.setVerticalGroup(
            convertPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convertPanel2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(convertPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 51, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AUTOMATION");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(294, 294, 294))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(16, 16, 16))
        );

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        label3.setText("Input a String to test:");

        testStringTf1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        testStringTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testStringTf1ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(102, 51, 255));
        jButton25.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("Check Acceptance");
        jButton25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(102, 102, 255));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Back");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        checkAcDFA.setVisible(false);

        javax.swing.GroupLayout checkAcDFALayout = new javax.swing.GroupLayout(checkAcDFA);
        checkAcDFA.setLayout(checkAcDFALayout);
        checkAcDFALayout.setHorizontalGroup(
            checkAcDFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(checkAcDFALayout.createSequentialGroup()
                .addGroup(checkAcDFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkAcDFALayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(checkAcDFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testStringTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkAcDFALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        checkAcDFALayout.setVerticalGroup(
            checkAcDFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkAcDFALayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(testStringTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(checkAcDFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.setVisible(false);
        loadFAPanel.setVisible(true);
        
        boolean isFirstLine = true;

        
        try (Scanner scanner = new Scanner(new File(DB_FILE_PATH))) {
            DefaultTableModel model=(DefaultTableModel) SavedDBtable.getModel();
            model.setRowCount(0);
            
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();

                // Skip the first line
                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }

                String[] parts = line.split(",");
                model.addRow(parts);
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(loadFAPanel, "Error reading CSV file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main.setVisible(false);
        Home2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Home2.setVisible(false);
        Main.setVisible(true);
        checkDeterministic2.setVisible(false);
        convertPanel2.setVisible(false);
        checkSavePanel2.setVisible(false);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
            int numStates=Integer.parseInt(numStatestf.getText());
            int numTrans=Integer.parseInt(NumTransTf.getText());
            
            String alphabetStr =alphaTF.getText();
            Set<Character> alphabet = new HashSet<>();
            for (String s : alphabetStr.split(" ")) {
                char c = s.charAt(0);
                alphabet.add(c == 'e' ? 'ε' : c);
            }

            String transInput=allTransTf.getText();
            String[] eachTrans=transInput.split(",");
            
            
        if(newFa.testFA(alphabet,numStates,numTrans,eachTrans)){
            JOptionPane.showMessageDialog(null, "This is a NFA!!! You can convert into DFA");
            convertPanel2.setVisible(true);
            checkDeterministic2.setVisible(false);
            checkAcDFA.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "This is a DFA");
            checkAcDFA.setVisible(true);
            checkDeterministic2.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Main.setVisible(true);
        checkDeterministic2.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        convertPanel2.setVisible(false);
        checkDeterministic2.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        checkSavePanel2.setVisible(true);
        convertPanel2.setVisible(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        checkSavePanel2.setVisible(false);
        convertPanel2.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        //get the data from user
        String numState=numStatestf.getText();
        String alphabets=alphaTF.getText();
        String startS=sStateTf.getText();
        String nTrans=NumTransTf.getText();
        String nFinalS=NumFStateTf.getText();
        String finalS=fStatesTf.getText();
        String originalTrans=allTransTf.getText();
        
        //change comma-seperated into semicolumn
        String[] eachOgTrans = originalTrans.split(",");
        StringBuilder semiCTrans = new StringBuilder();

        for (int i = 0; i < eachOgTrans.length; i++) {
            semiCTrans.append(eachOgTrans[i]);
            if (i < eachOgTrans.length - 1) {
                semiCTrans.append(";");
            }
        }
        String finalSemiCTrans = semiCTrans.toString();
        System.out.println(finalSemiCTrans);
        
        try (BufferedReader reader = new BufferedReader(new FileReader(DB_FILE_PATH))) {
                String line;
                String lastLine = null;

                while ((line = reader.readLine()) != null) {
                    lastLine = line;
                }

                // If the file is not empty, extract the ID from the last line
                if (lastLine != null) {
                    String[] values = lastLine.split(",");
                    String newID = values[0];
                    // Increment the employee ID for the new entry
                    newID = String.valueOf(Integer.parseInt(newID) + 1);
                    
                    // Continue with the rest of your code
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter(DB_FILE_PATH, true))) {
                        writer.write(newID + "," + numState + "," + alphabets + "," + startS + "," +
                                nTrans + "," + nFinalS + "," + finalS + "," + finalSemiCTrans);
                        writer.newLine(); // Add a new line for the next entry
                        JOptionPane.showMessageDialog(null, "Data successfully added to the CSV file.");
                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error adding data to the CSV file.");
                    }
                } else {
                    // If the file is empty, set a default value for the employee ID
                    String newID = "0";
                    // Continue with the rest of your code
                    // Continue with the rest of your code
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter(DB_FILE_PATH, true))) {
                        writer.write(newID + "," + numState + "," + alphabets + "," + startS + "," +
                                nTrans + "," + nFinalS + "," + finalS + "," + finalSemiCTrans);
                        writer.newLine(); // Add a new line for the next entry
                        JOptionPane.showMessageDialog(null, "Data successfully added to the CSV file.");
                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error adding data to the CSV file.");
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error reading the CSV file.");
            }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void NumFStateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumFStateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumFStateTfActionPerformed

    private void numStatestfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numStatestfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numStatestfActionPerformed

    private void alphaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphaTFActionPerformed

    private void sStateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sStateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sStateTfActionPerformed

    private void allTransTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTransTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allTransTfActionPerformed

    private void NumTransTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTransTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTransTfActionPerformed

    private void fStatesTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fStatesTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fStatesTfActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        checkSavePanel2.setVisible(false);
        checkAcDFA.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void testStringTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testStringTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testStringTf1ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        boolean isAccepted = newFa.testString(testStringTf1.getText());
        System.out.println(testStringTf1.getText());
            if (isAccepted) {
                JOptionPane.showMessageDialog(null, "Input is accepted by the DFA.");
                
            } else {
                JOptionPane.showMessageDialog(null, "Input is rejected by the DFA.");
                
            }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        checkAcDFA.setVisible(false);
        checkDeterministic2.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        checkAcDFA.setVisible(true);
        loadFAPanel.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void sStateTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sStateTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sStateTf1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        Main.setVisible(true);
        loadFAPanel.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        if(numStatestf.getText().equals("")||alphaTF.getText().equals("")||sStateTf.getText().equals("")|| NumFStateTf.getText().equals("") || fStatesTf.getText().equals("") 
                || NumTransTf.getText().equals("") ||allTransTf.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Please fill in all the boxes!!!");
        }else{

            
            //create new FA
            int numStates=Integer.parseInt(numStatestf.getText());
            Set<Integer> states = new HashSet<>();
            for (int i = 0; i < numStates; i++) {
                states.add(i);
            }

            String alphabetStr =alphaTF.getText();
            Set<Character> alphabet = new HashSet<>();
            for (String s : alphabetStr.split(" ")) {
                char c = s.charAt(0);
                alphabet.add(c == 'e' ? 'ε' : c);
            }

            int startState =Integer.parseInt(sStateTf.getText());

            int numFinalStates=Integer.parseInt(NumFStateTf.getText());


            String finalStateStr=fStatesTf.getText().trim();
            String[] eachfState=finalStateStr.split("\\s+");
            Set<Integer> finalStates = new HashSet<>();
            if(eachfState.length == numFinalStates){
                try{
                    for (int i = 0; i < eachfState.length; i++) {

                        System.out.print(Integer.valueOf(eachfState[i])); //testing

                        finalStates.add(Integer.valueOf(eachfState[i]));
                    }
                }catch(NumberFormatException e){
                    System.err.println("Invalid input number of final state not same as final state input");
                }
            }else{
                System.err.println("Invalid input number of final state not same as final state input");
            }

            newFa=new FA(states,alphabet,startState,finalStates);
            
            //transition
            boolean flag=false;
            String transInput=allTransTf.getText();
            String[] eachTrans=transInput.split(",");
		
		for(int i=0;i<eachTrans.length;i++) {
			String transition = eachTrans[i].trim();
			
			String[] eachChar=transition.split("\\s+");
			
			if (eachChar.length == 3) {
                        try {

                            int fromState = Integer.parseInt(eachChar[0]);
                            char input = eachChar[1].charAt(0);
                            int toState = Integer.parseInt(eachChar[2]);

                            newFa.addTransition(fromState, input == 'e' ? 'ε' : input, toState);
                            flag=true;
                            System.out.println("fromState: " + fromState + ", input: " + input + ", toState: " + toState);
                        } catch (NumberFormatException e) {
                            System.err.println("Invalid format in trans: " + transition);
                        }
                    } else {
                        System.err.println("Invalid format in trans: " + transition);
                    }
                }
            JOptionPane.showMessageDialog(null, "New Finite Automata has been created!!!");
            
            if(flag){
                Main.setVisible(false);
                checkDeterministic2.setVisible(true);
                Home2.setVisible(false);                
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        newDFA=Convertor.convertNFAtoDFA(newFa);
        JOptionPane.showMessageDialog(null, "Conversion has completed. Your NFA has turned to DFA");
        System.out.println(newDFA.states);
        System.out.println(newDFA.alphabet);
        System.out.println(newDFA.transitionFunction);
        System.out.println(newDFA.startState);
        System.out.println(newDFA.finalStates);
        
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomataProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomataProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomataProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomataProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomataProject().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home2;
    private javax.swing.JPanel Main;
    private java.awt.TextField NumFStateTf;
    private java.awt.TextField NumTransTf;
    private javax.swing.JTable SavedDBtable;
    private java.awt.TextField allTransTf;
    private java.awt.TextField alphaTF;
    private javax.swing.JPanel checkAcDFA;
    private javax.swing.JPanel checkDeterministic2;
    private javax.swing.JPanel checkSavePanel2;
    private javax.swing.JPanel convertPanel2;
    private java.awt.TextField fStatesTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JPanel loadFAPanel;
    private java.awt.TextField numStatestf;
    private java.awt.Panel panel2;
    private java.awt.TextField sStateTf;
    private java.awt.TextField sStateTf1;
    private java.awt.TextField testStringTf1;
    // End of variables declaration//GEN-END:variables
}
